# Database (MySQL / MariaDB)
DB_CONNECTION=main
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE={{DB_DATABASE}}
DB_USERNAME=root
DB_PASSWORD=
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci
DB_TIMEZONE=-04:00