# App
APP_NAME="{{PROJECT_TITLE}}"
APP_VERSION=1.0.0
APP_ENV=development
APP_DEBUG=true
APP_URL=http://localhost:{{PORT}}

{{DB_ENV}}

# CORS
CORS_ALLOWED_ORIGINS=*
CORS_ALLOWED_METHODS="GET, POST, PUT, DELETE, PATCH, OPTIONS"
CORS_ALLOWED_HEADERS="Content-Type, Authorization, X-Requested-With"
CORS_EXPOSED_HEADERS=""
CORS_MAX_AGE=86400
CORS_SUPPORTS_CREDENTIALS=false